// Package compose loads the project's compose files with compose-go, rewrites
// them for one isolated environment (project name, host ports, labels) and
// writes a single rendered file that `docker compose` runs unchanged.
package compose

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/compose-spec/compose-go/v2/cli"
	"github.com/compose-spec/compose-go/v2/types"

	"github.com/sam-bretz/envctl/internal/manifest"
	"github.com/sam-bretz/envctl/internal/ports"
)

// Labels applied to every service so `envctl list` can find environments
// without any local state.
const (
	LabelEnv     = "dev.envctl.env"
	LabelFeature = "dev.envctl.feature" // deprecated alias of LabelEnv, written for one release
	LabelBackend = "dev.envctl.backend"
	LabelProject = "dev.envctl.project"
)

// Mode is the resolved port strategy for a render.
type Mode string

const (
	ModeDomains  Mode = "domains"
	ModeRegistry Mode = "registry"
)

// Options drive one render.
type Options struct {
	Manifest *manifest.Manifest
	Env      string
	Branch   string
	Project  string
	Backend  string
	Mode     Mode
	Registry *ports.Registry // required for ModeRegistry
	OutDir   string          // where compose.yaml and env are written
	ExtraEnv map[string]string
}

// Published records one host port assignment made during render.
type Published struct {
	Service string
	Target  int
	Host    int
}

// Result is what a render produced.
type Result struct {
	File      string
	EnvFile   string
	Env       []string
	Published []Published
	Services  []string
}

// Render loads, rewrites and writes the compose project.
func Render(ctx context.Context, o Options) (*Result, error) {
	if o.Mode == ModeRegistry && o.Registry == nil {
		return nil, fmt.Errorf("registry mode requires a port registry")
	}
	project, err := load(ctx, o)
	if err != nil {
		return nil, err
	}
	res := &Result{}
	names := make([]string, 0, len(project.Services))
	for name := range project.Services {
		names = append(names, name)
	}
	sort.Strings(names)
	res.Services = names

	for _, name := range names {
		svc := project.Services[name]
		if svc.Labels == nil {
			svc.Labels = types.Labels{}
		}
		svc.Labels[LabelEnv] = o.Env
		svc.Labels[LabelFeature] = o.Env
		svc.Labels[LabelBackend] = o.Backend
		svc.Labels[LabelProject] = o.Project
		if svc.ContainerName != "" {
			// A fixed container_name makes two environments collide; namespace it.
			svc.ContainerName = o.Project + "-" + svc.ContainerName
		}
		rewritten, err := rewritePorts(o, name, svc.Ports, res)
		if err != nil {
			return nil, err
		}
		svc.Ports = rewritten
		project.Services[name] = svc
	}

	if err := os.MkdirAll(o.OutDir, 0o755); err != nil {
		return nil, err
	}
	raw, err := project.MarshalYAML()
	if err != nil {
		return nil, fmt.Errorf("marshal rendered project: %w", err)
	}
	header := "# Generated by envctl. Do not edit; edit the source compose files and re-run `envctl up`.\n"
	res.File = filepath.Join(o.OutDir, "compose.yaml")
	if err := os.WriteFile(res.File, append([]byte(header), raw...), 0o644); err != nil {
		return nil, err
	}

	res.Env = envLines(o, res)
	res.EnvFile = filepath.Join(o.OutDir, "env")
	if err := os.WriteFile(res.EnvFile, []byte(strings.Join(res.Env, "\n")+"\n"), 0o644); err != nil {
		return nil, err
	}
	return res, nil
}

func load(ctx context.Context, o Options) (*types.Project, error) {
	m := o.Manifest
	opts := []cli.ProjectOptionsFn{
		cli.WithName(o.Project),
		cli.WithWorkingDirectory(m.Dir),
		cli.WithOsEnv,
		cli.WithInterpolation(true),
		cli.WithResolvedPaths(true),
		cli.WithNormalization(true),
	}
	if envFiles := m.EnvFilePaths(); len(envFiles) > 0 {
		opts = append(opts, cli.WithEnvFiles(envFiles...), cli.WithDotEnv)
	}
	if len(o.ExtraEnv) > 0 {
		var kv []string
		for k, v := range o.ExtraEnv {
			kv = append(kv, k+"="+v)
		}
		opts = append(opts, cli.WithEnv(kv))
	}
	if len(m.Stack.Profiles) > 0 {
		opts = append(opts, cli.WithProfiles(m.Stack.Profiles))
	}
	po, err := cli.NewProjectOptions(m.StackPaths(), opts...)
	if err != nil {
		return nil, err
	}
	project, err := po.LoadProject(ctx)
	if err != nil {
		return nil, fmt.Errorf("load compose project: %w", err)
	}
	return project, nil
}

// rewritePorts applies the port mode. Domains mode drops host bindings so
// nothing can collide and services are reached by DNS. Registry mode replaces
// every host binding with a stable allocated port.
func rewritePorts(o Options, service string, in []types.ServicePortConfig, res *Result) ([]types.ServicePortConfig, error) {
	out := make([]types.ServicePortConfig, 0, len(in))
	for _, p := range in {
		target := int(p.Target)
		if p.Published == "" {
			out = append(out, p)
			continue
		}
		switch o.Mode {
		case ModeDomains:
			// Keep the container port exposed; drop the host binding.
			continue
		case ModeRegistry:
			host, err := o.Registry.Get(ports.Key{Project: o.Project, Service: service, Target: target})
			if err != nil {
				return nil, err
			}
			p.Published = strconv.Itoa(host)
			p.HostIP = "127.0.0.1"
			res.Published = append(res.Published, Published{Service: service, Target: target, Host: host})
			out = append(out, p)
		default:
			return nil, fmt.Errorf("unknown port mode %q", o.Mode)
		}
	}
	return out, nil
}

// envLines produces KEY=VALUE pairs that host-side tooling (Makefiles, native
// test runners, agents) can source to reach the environment.
func envLines(o Options, res *Result) []string {
	lines := []string{
		"ENVCTL_ENV=" + o.Env,
		"ENVCTL_FEATURE=" + o.Env, // deprecated alias
		"ENVCTL_BRANCH=" + o.Branch,
		"ENVCTL_PROJECT=" + o.Project,
		"ENVCTL_BACKEND=" + o.Backend,
		"ENVCTL_PORT_MODE=" + string(o.Mode),
	}
	for _, s := range res.Services {
		key := "ENVCTL_HOST_" + envKey(s)
		if o.Mode == ModeDomains {
			lines = append(lines, key+"="+DomainHost(s, o.Project))
		} else {
			lines = append(lines, key+"=127.0.0.1")
		}
	}
	for _, p := range res.Published {
		lines = append(lines, fmt.Sprintf("ENVCTL_PORT_%s_%d=%d", envKey(p.Service), p.Target, p.Host))
	}
	sort.Strings(lines[6:])
	return lines
}

// DomainHost is OrbStack's per-service DNS name for a compose project.
func DomainHost(service, project string) string {
	return service + "." + project + ".orb.local"
}

func envKey(s string) string {
	return strings.ToUpper(strings.NewReplacer("-", "_", ".", "_").Replace(s))
}
